# Generated by Django 2.1.5 on 2019-02-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
