# Generated by Django 2.1.5 on 2019-02-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_img_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img_acc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
